### ISSUE TITLE
Team Meeting 3/21/2023 4PM

### ISSUE THREAD

**Issue by HeavenlyRain** [EECE3093C/team-project-lua#19]
# Goal of this issue

Document team meeting

# Resources

Please see the discord discussion channel where information was placed regarding questions and blocks

**Comment by BinniesLite** [comment]
### Summary

The team discuss what is missing from the git repo and how to approach the task from now forward, we also decide that because devcontainer is not working correctly with the front-end stack so we will put that issue to another time and prioritize the development of the project. The backend will have working api ready to be called and have some documentation of the api

**Comment by HeavenlyRain** [comment]
Discussed security strategy regarding user password and authentication. 

Will the user login using email or username? Passwords will be hashed and stored on the PostgreSQL database.

**Comment by HeavenlyRain** [comment]
Provided initial mockups for client landing page

**Comment by HeavenlyRain** [comment]
Discussed GitHub actions and the appropriate time for implementing the CI/CD solution.

Concluded to implement in next iteration.

**Comment by HeavenlyRain** [comment]
Discussed the addition of CRUD utilities to the current server version. 

Currently working on finishing user CRUD utilities. (Getting user information and creating users)

**Comment by HeavenlyRain** [comment]
Spoke about the current branching strategy and implementation of the provided standards by the instructor.
